In [1]:
import mynn
from mynn.layers.dense import dense
from mynn.optimizers.sgd import SGD
from mygrad.nnet.losses.margin_ranking_loss import margin_ranking_loss
import mygrad as mg
from noggin import create_plot
import numpy as np
import pickle
from mygrad.nnet.initializers import glorot_normal
%matplotlib notebook

In [2]:
from coco_class import Coco
from generate_triplets import generate_triplets
class Img2Caption:
    def __init__(self, dim_input: int, dim_output: int):
        """
        Initializes the Img2Caption Linear Encoder
        Parameters
        ----------
        dim_input the dimensions of the input descriptor
        dim_output the dimensions of the encoded value
        """
        self.layer = dense(dim_input, dim_output, weight_initializer=glorot_normal)
        
    def __call__(self, descriptor):
        """
        Runs the forward pass of the model
        Parameters
        ----------
        descriptor the descriptor vector to be processed

        Returns
        -------
        The shape-(dim_output) embedding

        """
        result = self.layer(descriptor)
        magnitude = mg.sqrt(mg.sum(mg.square(result), axis = 1, keepdims=True))
        print(f"Magnitude: {magnitude}")
        return result / magnitude
    
    @property
    def parameters(self):
        """
        Returns the parameters of the encoding layer
        Returns
        -------
        The parameters of the encoding layer
        """
        return self.layer.parameters

In [3]:
data = Coco()

glove loaded


UnsupportedError: Failed in nopython mode pipeline (step: inline calls to locally defined closures)
The use of yield in a closure is unsupported.

File "coco_class.py", line 202:
    def to_idf(self, vocab, counters):
        <source elided>
        N = len(counters)
        nt = [sum(1 if t in counter else 0 for counter in counters) for t in vocab]
        ^


In [ ]:
model = Img2Caption(512, 50)
lr = 1e-3
momentum = 0.9
optim = SGD(model.parameters, learning_rate = lr, momentum = momentum)


In [ ]:
plotter, figs, axes = create_plot(metrics=["loss", "accuracy"])

In [ ]:
# data = Coco()
with open("temp_cd.pkl", mode="rb") as file:
    data = pickle.load(file)


In [ ]:

# train, validation = generate_triplets(data) # List(Tuple[]), Shape (N,)
with open("train_triplets_v1.pkl", mode="rb") as file:
    train = pickle.load(file)
with open("val_triplets_v1.pkl", mode="rb") as file:
    validation = pickle.load(file)

In [32]:
train_d_good = np.zeros((len(train), 512))
for i in range(len(train)):
    train_d_good[i] = train[i][0].reshape(512)
train_w_good = np.zeros((len(train), 50))
for i in range(len(train)):
    train_w_good[i] = train[i][1].reshape(50)
train_d_bad = np.zeros((len(train), 512))
for i in range(len(train)):
    train_d_bad[i] = train[i][2].reshape(512)
    
val_d_good = np.zeros((len(validation), 512))
for i in range(len(validation)):
    val_d_good[i] = validation[i][0].reshape(512)
val_w_good = np.zeros((len(validation), 50))
for i in range(len(validation)):
    val_w_good[i] = validation[i][1].reshape(50)
val_d_bad = np.zeros((len(validation), 512))
for i in range(len(validation)):
    val_d_bad[i] = validation[i][2].reshape(512)

train = (train_d_good[::2], train_w_good[::2], train_d_bad[::2])
validation = (val_d_good[::2], val_w_good[::2], val_d_bad[::2])

In [8]:
d_img = train[0]
print(len(d_img))

330415


In [48]:
idx = np.arange(len(train[0]))
b = idx[:32]
bd_img = d_img[b]
bw_good = w_good[b]
bd_bad = d_bad[b]

w_bad = model(bd_bad) # Shape (32, 50)
w_img = model(bd_img)
dot_good = mg.sum(w_img * bw_good, axis=1) # Shape (32,)
dot_bad = mg.sum(bw_good * w_bad, axis=1) # Shape (32,)

loss = margin_ranking_loss(dot_good, dot_bad, 1, margin=0.1)


print(w_bad)
print(w_img)
print(dot_good.max())
print(dot_good.min())
print(dot_bad.max())
print(dot_bad.min())

loss.backward()
print(model.layer.weight.grad)

Tensor([[ 0.07102041,  0.04983361,  0.0343528 , ...,  0.19443091,
          0.03889689, -0.09427323],
        [-0.03451658, -0.10148807, -0.12066847, ...,  0.1108868 ,
         -0.08822447,  0.15261918],
        [ 0.06754778,  0.09816844, -0.04274904, ...,  0.28116812,
          0.03204005,  0.13971078],
        ...,
        [ 0.08709974,  0.03563017, -0.05917015, ...,  0.00778787,
          0.05407839,  0.02655266],
        [ 0.05693169,  0.09842793,  0.27056281, ..., -0.07260665,
          0.10194122,  0.14205077],
        [-0.1219042 ,  0.03351373,  0.10670598, ...,  0.08469758,
          0.0314163 ,  0.14988822]])
Tensor([[ 0.10788981, -0.05371741,  0.08718307, ...,  0.22560639,
          0.09745083,  0.34326418],
        [ 0.10788981, -0.05371741,  0.08718307, ...,  0.22560639,
          0.09745083,  0.34326418],
        [ 0.10788981, -0.05371741,  0.08718307, ...,  0.22560639,
          0.09745083,  0.34326418],
        ...,
        [ 0.1145021 ,  0.02416583,  0.03840153, ..., -0

In [68]:
epochs = 5
batch_size = 32

d_img = train[0]
w_good = train[1]
w_good = w_good / np.linalg.norm(w_good, axis=1, keepdims=True)
d_bad = train[2]
for ep in range(epochs):
    idx = np.arange(len(train[0]))
    np.random.shuffle(idx)
    for batch_cnt in range(len(train[0]) // batch_size + 1):
        b = idx[batch_cnt * batch_size:(batch_cnt + 1) * batch_size]
        
        bd_img = d_img[b]
        bw_good = w_good[b]
        bd_bad = d_bad[b]
        
        w_bad = model(bd_bad) # Shape (32, 50)
        w_img = model(bd_img) # Shape (32, 50)
        
        dot_good = mg.sum(w_img * bw_good, axis=1) # Shape (32,)
        print(dot_good.mean())
            
        dot_bad = mg.sum(bw_good * w_bad, axis=1) # Shape (32,)
        print(dot_bad.mean())
        acc = np.mean(dot_good > dot_bad)
        
        loss = margin_ranking_loss(dot_good, dot_bad, 1, margin=0.1)

#         loss.backward()

#         optim.step()

#         loss.null_gradients()

        plotter.set_train_batch(metrics={"loss": loss.item(), "accuracy":acc}, batch_size=batch_size)

    plotter.set_train_epoch()


Magnitude: Tensor([[ 9.41932989],
        [14.05186485],
        [15.00650524],
        [13.96475659],
        [10.87193519],
        [11.23819091],
        [12.12576711],
        [14.620452  ],
        [11.95419195],
        [12.43597413],
        [13.60161625],
        [10.94133258],
        [13.99833998],
        [10.20221382],
        [12.4920618 ],
        [14.16406901],
        [10.50251005],
        [11.6349799 ],
        [11.70527585],
        [12.11070562],
        [13.16509561],
        [10.6547747 ],
        [13.86550942],
        [ 9.1911298 ],
        [13.08523392],
        [17.25232339],
        [11.52983391],
        [13.92606404],
        [11.30884783],
        [12.6674169 ],
        [16.10357274],
        [10.39388921]])
Magnitude: Tensor([[15.5219487 ],
        [15.84724731],
        [11.92386867],
        [10.17013627],
        [14.55503955],
        [14.04881801],
        [14.68165111],
        [11.39025454],
        [12.28931301],
        [ 9.98029949],
        [12

        [11.42369339]])
Magnitude: Tensor([[10.29800529],
        [11.04267398],
        [13.42107229],
        [11.91699105],
        [13.17943801],
        [14.87548186],
        [10.6766481 ],
        [12.30645157],
        [10.55042199],
        [12.3647517 ],
        [13.67247027],
        [14.2242488 ],
        [10.41762397],
        [13.64283672],
        [13.95809194],
        [11.98186505],
        [13.18236541],
        [10.31333988],
        [12.34982823],
        [11.67667743],
        [ 9.71310886],
        [11.29765447],
        [10.46090148],
        [11.56447483],
        [11.07153615],
        [13.34421882],
        [12.57609484],
        [12.99515012],
        [12.17072816],
        [ 9.71964391],
        [11.44518983],
        [11.01651885]])
Tensor(nan)
Tensor(nan)
Magnitude: Tensor([[ 9.16966855],
        [11.90934898],
        [11.37919327],
        [12.53444679],
        [12.51066698],
        [11.4246511 ],
        [13.22395775],
        [12.15744071],
        [

        [11.87987526]])
Tensor(nan)
Tensor(nan)
Magnitude: Tensor([[13.42234896],
        [ 8.63618006],
        [14.78653499],
        [11.10102329],
        [14.36984339],
        [10.20872081],
        [11.90458504],
        [11.63171907],
        [13.61379067],
        [10.44469422],
        [13.08234822],
        [11.28475709],
        [11.56624979],
        [11.86941495],
        [13.69309812],
        [10.30477612],
        [11.84480524],
        [16.30574347],
        [12.87806285],
        [11.52397114],
        [11.49255661],
        [11.84938569],
        [11.36841451],
        [12.09462755],
        [11.84566234],
        [11.88893113],
        [15.61998591],
        [13.19391588],
        [ 9.66875983],
        [11.29625851],
        [11.6311987 ],
        [13.14918294]])
Magnitude: Tensor([[11.98455992],
        [11.35707492],
        [13.89703641],
        [12.54291298],
        [13.78763454],
        [10.88045389],
        [10.31282073],
        [15.5242554 ],
        [

        [10.44009415]])
Magnitude: Tensor([[11.59821234],
        [14.70191613],
        [15.18207873],
        [13.37980072],
        [13.64998099],
        [12.12886019],
        [12.19582961],
        [13.51829405],
        [12.86185432],
        [10.52619899],
        [12.4107139 ],
        [13.50327211],
        [12.7692449 ],
        [11.65499897],
        [11.50975243],
        [11.33279257],
        [14.76593287],
        [14.51429314],
        [13.98934656],
        [11.79214838],
        [14.59007329],
        [12.55768918],
        [15.32875842],
        [14.3424996 ],
        [ 9.2753249 ],
        [10.59382029],
        [13.57106221],
        [11.85657123],
        [14.03823684],
        [ 9.16413082],
        [15.43876568],
        [ 9.57167652]])
Tensor(nan)
Tensor(nan)
Magnitude: Tensor([[10.04402993],
        [16.99460905],
        [14.54497871],
        [13.37828084],
        [ 9.89164314],
        [15.78658596],
        [12.96683117],
        [11.85504823],
        [

        [11.16036844]])
Magnitude: Tensor([[12.66674025],
        [11.21930095],
        [10.3029866 ],
        [14.00786075],
        [12.66997351],
        [10.28631914],
        [13.10331625],
        [14.29934654],
        [15.67153557],
        [10.15183701],
        [12.83581993],
        [11.51924588],
        [10.88088265],
        [11.23441   ],
        [11.16469594],
        [13.56892157],
        [10.90224248],
        [12.72182979],
        [12.96741812],
        [14.42030774],
        [14.47407961],
        [15.63405084],
        [12.94538389],
        [12.63393709],
        [14.01927888],
        [11.59433799],
        [11.1290627 ],
        [15.03788986],
        [12.62773279],
        [13.6958252 ],
        [15.6986829 ],
        [14.17139478]])
Tensor(-0.10413073)
Tensor(-0.12446104)
Magnitude: Tensor([[13.41548963],
        [11.26200795],
        [11.4113053 ],
        [13.40430157],
        [11.89755153],
        [13.33158947],
        [ 8.91310597],
        [13.6825

        [11.8488099 ]])
Magnitude: Tensor([[10.63370996],
        [12.33004619],
        [14.56870048],
        [12.56439415],
        [10.28289773],
        [13.36734232],
        [10.51354377],
        [11.54223562],
        [14.85582869],
        [14.42415117],
        [12.47254964],
        [14.79989369],
        [12.11873516],
        [12.11043187],
        [12.69941955],
        [14.68678353],
        [12.96938704],
        [11.47783528],
        [11.37803438],
        [11.6566636 ],
        [12.42495089],
        [10.62495016],
        [10.99113932],
        [12.34817866],
        [12.99546429],
        [ 9.28781938],
        [13.03042682],
        [15.26964372],
        [ 8.44040335],
        [12.72056389],
        [14.89491406],
        [11.22241489]])
Tensor(-0.08780762)
Tensor(-0.12167764)
Magnitude: Tensor([[14.67214749],
        [11.95382985],
        [10.83141288],
        [14.79965224],
        [14.74139282],
        [13.22670777],
        [11.06857033],
        [11.0424

Magnitude: Tensor([[11.7040546 ],
        [11.07669004],
        [11.35709096],
        [15.39141596],
        [13.16172646],
        [11.57481044],
        [12.2544682 ],
        [15.56944054],
        [15.10600282],
        [14.25635721],
        [13.1428857 ],
        [10.10224189],
        [12.17390898],
        [10.40609504],
        [13.03878939],
        [10.27193082],
        [16.89082645],
        [11.71370912],
        [ 8.87766148],
        [13.72464163],
        [12.50858448],
        [10.60627408],
        [16.30843995],
        [12.4384558 ],
        [ 9.52633285],
        [10.97020979],
        [12.54637313],
        [10.58260884],
        [11.18466278],
        [14.9407213 ],
        [11.8046669 ],
        [12.14595609]])
Tensor(-0.10753457)
Tensor(-0.08633802)
Magnitude: Tensor([[11.94992684],
        [ 9.62139586],
        [11.4186372 ],
        [14.56616856],
        [13.85606898],
        [10.87975685],
        [10.86599816],
        [12.20111655],
        [11.19199

Tensor(-0.08415121)
Magnitude: Tensor([[11.46268139],
        [14.71728847],
        [11.58748241],
        [11.05770044],
        [12.97087817],
        [11.69415657],
        [11.51237845],
        [10.24003648],
        [11.21722754],
        [12.89953208],
        [ 8.86740978],
        [10.60563826],
        [12.01283649],
        [13.31059441],
        [14.38241942],
        [ 9.82692201],
        [13.68064479],
        [11.59075083],
        [12.55794935],
        [10.53411075],
        [ 9.89952217],
        [10.70389047],
        [ 9.90839582],
        [12.58040183],
        [13.87106038],
        [14.54138879],
        [14.36979324],
        [16.05699642],
        [14.16361056],
        [13.38249393],
        [10.05736344],
        [13.12547577]])
Magnitude: Tensor([[13.39039203],
        [11.40331185],
        [11.74597963],
        [12.28867042],
        [13.43199408],
        [15.38529502],
        [10.81188718],
        [13.60647241],
        [13.65304414],
        [12.96

        [12.78174495]])
Magnitude: Tensor([[12.6180777 ],
        [12.66828987],
        [13.02733971],
        [12.24077478],
        [11.74340308],
        [11.91072188],
        [11.09364769],
        [13.45278599],
        [12.01934216],
        [11.22848544],
        [14.26034726],
        [11.59269653],
        [13.28817881],
        [12.13583159],
        [15.19786629],
        [13.1299671 ],
        [12.76043779],
        [10.75434776],
        [ 7.91202174],
        [13.90506542],
        [11.17155509],
        [ 9.0556681 ],
        [12.17394492],
        [10.42085049],
        [11.81593965],
        [13.62658739],
        [14.10698657],
        [10.94226629],
        [13.4377921 ],
        [15.91151958],
        [10.19825269],
        [12.11354111]])
Tensor(-0.08921877)
Tensor(-0.08927237)
Magnitude: Tensor([[ 9.06192848],
        [14.79627205],
        [ 9.64375498],
        [13.90759069],
        [13.71611887],
        [13.82797835],
        [ 9.92936187],
        [12.0224

Tensor(nan)
Magnitude: Tensor([[12.55872468],
        [11.04121845],
        [12.14462439],
        [12.16861465],
        [13.88777893],
        [13.96614194],
        [10.1989704 ],
        [12.05361582],
        [14.46165574],
        [11.74686669],
        [10.03685685],
        [11.41701321],
        [12.66339468],
        [12.27313786],
        [12.51141691],
        [12.39958326],
        [13.24554109],
        [13.42166906],
        [11.24000877],
        [13.62886622],
        [10.13224225],
        [10.56055126],
        [11.01891155],
        [11.41668747],
        [13.56574358],
        [11.89618141],
        [11.57373614],
        [14.53308526],
        [10.45806794],
        [11.22232097],
        [11.16824992],
        [13.1859314 ]])
Magnitude: Tensor([[12.0935383 ],
        [14.05667318],
        [11.93389497],
        [15.25855879],
        [11.34662704],
        [12.50159876],
        [12.18323111],
        [14.40460665],
        [13.09438404],
        [12.65756715],

        [16.0252357 ]])
Tensor(nan)
Tensor(nan)
Magnitude: Tensor([[11.54436204],
        [13.67072219],
        [11.66076391],
        [11.6012848 ],
        [12.79906113],
        [10.21486383],
        [12.99452887],
        [13.36434221],
        [ 9.12432829],
        [ 9.22029223],
        [12.15938697],
        [11.56204518],
        [11.49373213],
        [13.93929754],
        [12.35994197],
        [10.71174916],
        [10.86265511],
        [10.87580703],
        [15.76873314],
        [13.74128516],
        [13.82722433],
        [13.89309005],
        [10.59382029],
        [12.66597711],
        [12.07075415],
        [11.97933169],
        [12.79466588],
        [13.20456658],
        [12.7449457 ],
        [12.17271156],
        [11.82792735],
        [11.89765226]])
Magnitude: Tensor([[12.07477323],
        [11.95362734],
        [12.35489727],
        [ 9.8021527 ],
        [11.29707718],
        [13.29015796],
        [13.54453216],
        [13.17556451],
        [

Tensor(-0.09142702)
Tensor(-0.0839488)
Magnitude: Tensor([[12.57025786],
        [12.78285418],
        [11.54033501],
        [16.06166919],
        [11.45163956],
        [12.58233591],
        [11.66794585],
        [11.58508321],
        [11.41248225],
        [ 9.94472889],
        [12.82399244],
        [10.23591354],
        [10.59432363],
        [11.16646382],
        [11.33494353],
        [14.30183884],
        [11.84503155],
        [11.84030416],
        [12.19536054],
        [14.21591008],
        [14.40194639],
        [15.10477912],
        [12.66806156],
        [ 9.62923345],
        [14.26938927],
        [13.95363038],
        [13.4450118 ],
        [13.48903226],
        [11.23770228],
        [11.62345435],
        [12.56550001],
        [16.2273365 ]])
Magnitude: Tensor([[14.41423635],
        [13.13585327],
        [14.6278564 ],
        [11.66331075],
        [16.05159247],
        [13.15007854],
        [15.49031638],
        [10.05064713],
        [15.420722

        [12.85640847]])
Magnitude: Tensor([[15.90347468],
        [10.49618555],
        [ 9.3321433 ],
        [11.49082134],
        [13.70596761],
        [12.67587658],
        [15.31889253],
        [10.75879382],
        [13.98949494],
        [13.52838382],
        [13.05956846],
        [13.94890873],
        [13.36459198],
        [10.01153601],
        [11.05411499],
        [11.54981519],
        [12.88607867],
        [13.75633475],
        [11.13063702],
        [11.84573241],
        [10.39260261],
        [12.45801946],
        [12.03351591],
        [12.15902509],
        [13.98559046],
        [14.60182209],
        [11.95130192],
        [10.33995484],
        [10.25859169],
        [11.98926087],
        [12.19204392],
        [13.37679429]])
Tensor(nan)
Tensor(nan)
Magnitude: Tensor([[13.41287879],
        [13.87305412],
        [11.70216112],
        [16.08508184],
        [10.30589308],
        [13.1970298 ],
        [14.08983195],
        [10.65149751],
        [

        [11.38930009]])
Tensor(-0.09770069)
Tensor(-0.06307663)
Magnitude: Tensor([[11.48303169],
        [11.43071504],
        [11.70394735],
        [11.93767536],
        [10.70919201],
        [13.10072538],
        [11.26359451],
        [ 9.96818548],
        [14.21522557],
        [12.05702802],
        [15.12448354],
        [11.7773177 ],
        [11.16560565],
        [14.82140833],
        [12.00402018],
        [10.6851473 ],
        [11.73474316],
        [11.49525003],
        [10.71957115],
        [11.03393806],
        [12.56425122],
        [12.9343159 ],
        [13.17514647],
        [11.6833577 ],
        [14.42737966],
        [13.26564649],
        [11.65928443],
        [12.03739746],
        [11.79613071],
        [12.56359769],
        [10.92649996],
        [13.36232636]])
Magnitude: Tensor([[11.47537328],
        [12.09011812],
        [10.66488428],
        [14.71982902],
        [12.8902515 ],
        [10.51554381],
        [12.95766385],
        [10.2098

Tensor(-0.09721885)
Magnitude: Tensor([[14.23326269],
        [12.11437579],
        [11.73413806],
        [12.2180655 ],
        [15.52820432],
        [10.22687464],
        [ 8.89054184],
        [13.04036638],
        [12.2247065 ],
        [11.15001626],
        [13.12564301],
        [15.16050253],
        [14.91597544],
        [11.46478894],
        [12.77353334],
        [13.25711124],
        [10.8811766 ],
        [13.65497696],
        [11.05478096],
        [12.94368681],
        [15.11536226],
        [11.74296869],
        [13.91504442],
        [11.90942883],
        [14.22907908],
        [11.24858478],
        [11.90792991],
        [13.59315199],
        [12.21887893],
        [11.86429393],
        [10.8077821 ],
        [11.42898403]])
Magnitude: Tensor([[11.35450747],
        [11.05149463],
        [13.6165549 ],
        [12.39971364],
        [13.57253683],
        [11.82177155],
        [13.70889145],
        [13.21250693],
        [14.84380483],
        [10.48

        [13.65356495]])
Magnitude: Tensor([[14.37601104],
        [14.28038379],
        [10.56987594],
        [11.42880482],
        [11.89913577],
        [12.31354612],
        [11.54404256],
        [10.47510073],
        [ 9.66655225],
        [13.93522754],
        [14.67311236],
        [14.06401556],
        [12.1057071 ],
        [11.60770093],
        [13.80004697],
        [11.8798518 ],
        [11.95690389],
        [ 9.81405459],
        [11.12962942],
        [15.20902427],
        [11.495169  ],
        [13.09670785],
        [11.08892981],
        [10.91283062],
        [13.93060319],
        [ 9.4541026 ],
        [15.34725822],
        [ 9.95169013],
        [12.34969564],
        [ 9.49388646],
        [17.88178445],
        [11.95784258]])
Tensor(-0.08785617)
Tensor(-0.1136482)
Magnitude: Tensor([[13.94222906],
        [12.63817332],
        [16.2521786 ],
        [12.53955031],
        [13.35727231],
        [11.26134966],
        [ 8.86849086],
        [13.48893

        [12.89730505]])
Tensor(nan)
Tensor(nan)
Magnitude: Tensor([[10.66332373],
        [13.51521738],
        [11.43212222],
        [13.71633516],
        [13.60148948],
        [11.15518165],
        [12.54819793],
        [13.9045512 ],
        [12.28314592],
        [11.18530817],
        [13.74189188],
        [ 8.35604681],
        [12.11966702],
        [15.06989403],
        [12.77627512],
        [11.61777873],
        [13.98289681],
        [12.92729952],
        [12.64142567],
        [14.52261947],
        [ 9.73055332],
        [11.26426547],
        [13.33931695],
        [13.06321896],
        [11.49004197],
        [12.19581771],
        [11.04677769],
        [11.22320019],
        [ 9.44975722],
        [13.84051522],
        [13.50076871],
        [13.16748841]])
Magnitude: Tensor([[12.13019037],
        [ 9.94768635],
        [ 9.23871821],
        [14.64506544],
        [ 8.36853151],
        [12.63595396],
        [10.27231691],
        [ 9.70484645],
        [

Tensor(-0.09014498)
Tensor(-0.10550287)
Magnitude: Tensor([[ 9.79793078],
        [11.84627212],
        [12.19792936],
        [14.03185437],
        [13.6142487 ],
        [ 8.01806912],
        [ 9.14532409],
        [13.38989829],
        [13.48351693],
        [13.42527904],
        [13.9034687 ],
        [14.96962034],
        [15.78890198],
        [11.80524557],
        [12.91060949],
        [ 9.95372552],
        [12.0124155 ],
        [14.4706069 ],
        [12.60630543],
        [11.42158541],
        [11.69549263],
        [15.49429819],
        [10.59280109],
        [14.29511908],
        [12.32706773],
        [13.41667028],
        [14.87555322],
        [13.89203248],
        [12.92011307],
        [13.12391278],
        [13.42857983],
        [12.77400215]])
Magnitude: Tensor([[12.07869733],
        [11.71884076],
        [10.20939315],
        [12.61438611],
        [13.98626942],
        [12.1570101 ],
        [10.80963558],
        [16.07085018],
        [11.69337

Magnitude: Tensor([[13.1396609 ],
        [12.3752935 ],
        [15.75035093],
        [10.9354106 ],
        [13.78496934],
        [16.22998911],
        [13.42763523],
        [13.41430373],
        [11.74173228],
        [ 9.10720135],
        [13.61666385],
        [15.28825722],
        [12.36029872],
        [12.21439747],
        [13.62927189],
        [11.94474102],
        [11.15109425],
        [13.39745105],
        [14.30958721],
        [10.7929502 ],
        [ 9.88368235],
        [12.36220387],
        [12.18947472],
        [14.98252837],
        [10.37641873],
        [12.60902973],
        [12.48290571],
        [11.98839306],
        [12.33975196],
        [11.05762717],
        [12.07217218],
        [ 9.92226256]])
Magnitude: Tensor([[12.32317895],
        [13.63809412],
        [11.29070607],
        [11.84614562],
        [11.56645137],
        [15.38521024],
        [10.51290464],
        [12.36429507],
        [12.73252383],
        [12.00454408],
        [12

        [14.00694691]])
Tensor(nan)
Tensor(nan)
Magnitude: Tensor([[14.09251849],
        [10.76716044],
        [11.31510352],
        [12.99359793],
        [11.59219147],
        [13.15812859],
        [10.82011984],
        [10.86345771],
        [10.19054784],
        [11.40454415],
        [13.88985279],
        [15.10236786],
        [ 9.44627364],
        [12.22191131],
        [12.49575603],
        [13.55099325],
        [11.19565273],
        [12.62571892],
        [12.55139975],
        [ 9.73619244],
        [11.96396208],
        [12.38851541],
        [11.77903574],
        [12.62488466],
        [12.41471108],
        [14.95294653],
        [10.92623253],
        [18.66801034],
        [14.67426054],
        [13.08434113],
        [13.3088877 ],
        [11.60318703]])
Magnitude: Tensor([[12.06298834],
        [12.55945523],
        [10.28406949],
        [10.73663772],
        [12.26284364],
        [15.23516822],
        [13.0158085 ],
        [12.36571866],
        [

        [13.49927696]])
Magnitude: Tensor([[13.41032851],
        [ 7.57875773],
        [14.03780634],
        [12.07863201],
        [12.8881059 ],
        [12.2106689 ],
        [11.92894506],
        [ 9.7165956 ],
        [11.75364917],
        [13.38064641],
        [13.56574358],
        [13.82206318],
        [12.6071884 ],
        [14.82889265],
        [13.42930724],
        [10.9539433 ],
        [11.14631297],
        [10.61482954],
        [14.04885676],
        [15.01524558],
        [13.05909542],
        [10.33751765],
        [11.6540471 ],
        [13.51654256],
        [12.93430033],
        [11.84906227],
        [11.53881283],
        [14.77399408],
        [14.52048332],
        [11.38902998],
        [11.63949272],
        [12.34760981]])
Tensor(-0.1115191)
Tensor(-0.12416504)
Magnitude: Tensor([[16.23846583],
        [13.61994045],
        [11.49585142],
        [12.98390195],
        [ 9.22196323],
        [ 9.8899997 ],
        [13.82633837],
        [13.11350

        [11.91100388]])
Tensor(-0.07656055)
Tensor(-0.09569802)
Magnitude: Tensor([[ 9.3583059 ],
        [13.56135968],
        [17.18482038],
        [12.74434405],
        [15.57459817],
        [12.6749574 ],
        [11.73752137],
        [12.87805661],
        [10.98417265],
        [11.46153084],
        [10.30862588],
        [12.58714216],
        [13.07144441],
        [11.43822851],
        [12.4858786 ],
        [10.27201007],
        [ 8.79623455],
        [15.33608851],
        [13.25711124],
        [13.27460747],
        [12.67068976],
        [13.53793176],
        [11.30744685],
        [10.93150545],
        [15.70279085],
        [ 9.67509906],
        [11.95884367],
        [14.6276312 ],
        [11.65067419],
        [10.17705512],
        [14.21191031],
        [13.71558748]])
Magnitude: Tensor([[17.28696771],
        [13.41384576],
        [11.16843837],
        [12.97313515],
        [16.77476128],
        [12.51066698],
        [12.27053606],
        [12.2689

        [12.62703921]])
Tensor(-0.07894554)
Tensor(-0.057825)
Magnitude: Tensor([[10.1986739 ],
        [12.17233447],
        [13.59474429],
        [14.25201046],
        [13.66379209],
        [10.60808641],
        [ 9.7545832 ],
        [11.02458955],
        [ 9.84098241],
        [12.00623758],
        [16.84579964],
        [12.68339799],
        [11.59485819],
        [10.71744761],
        [13.89273775],
        [10.70785023],
        [15.8991922 ],
        [14.96348087],
        [11.7118739 ],
        [11.77525742],
        [16.47003785],
        [13.39751015],
        [14.49836916],
        [19.04253101],
        [11.88986244],
        [14.83394656],
        [12.83251703],
        [10.77977147],
        [11.73089257],
        [11.38248216],
        [12.50499386],
        [11.43425463]])
Magnitude: Tensor([[12.2247065 ],
        [12.64301129],
        [11.01099856],
        [14.99864636],
        [10.67517642],
        [12.08933133],
        [13.29303204],
        [14.368524

        [10.72456263]])
Magnitude: Tensor([[10.21586453],
        [10.38424846],
        [14.89227227],
        [13.5786451 ],
        [12.2808377 ],
        [11.61761602],
        [10.19566242],
        [10.14344291],
        [13.8797016 ],
        [11.29056376],
        [11.69626647],
        [11.66966164],
        [13.80791361],
        [10.89192259],
        [14.58675726],
        [13.9821591 ],
        [17.12410999],
        [11.50560703],
        [12.74273235],
        [12.68350008],
        [13.94548028],
        [12.74226345],
        [ 9.27270916],
        [ 9.78820059],
        [12.6359597 ],
        [10.5276111 ],
        [14.61943251],
        [16.30708291],
        [12.50084927],
        [15.53344057],
        [13.87733041],
        [10.96585247]])
Tensor(-0.08838571)
Tensor(-0.0674833)
Magnitude: Tensor([[11.32020228],
        [11.61934348],
        [11.47556091],
        [13.14321492],
        [14.38796441],
        [11.32188119],
        [12.73573367],
        [13.10400

Tensor(-0.09232195)
Tensor(-0.09173658)
Magnitude: Tensor([[11.82062001],
        [13.1634994 ],
        [13.6061012 ],
        [12.85228921],
        [12.17632995],
        [11.5396851 ],
        [11.93276204],
        [11.50962006],
        [12.82006381],
        [13.57815747],
        [13.78481057],
        [13.31245719],
        [13.3487591 ],
        [11.20607042],
        [15.06254931],
        [14.1945398 ],
        [12.55457876],
        [16.263582  ],
        [15.87022986],
        [16.82675119],
        [11.046788  ],
        [14.47975075],
        [14.20428487],
        [16.59528031],
        [11.99667275],
        [14.56419928],
        [12.23762523],
        [ 9.76138291],
        [16.38403499],
        [15.61861467],
        [12.0503718 ],
        [10.82360164]])
Magnitude: Tensor([[13.3783709 ],
        [12.06423862],
        [12.94836845],
        [13.0943368 ],
        [11.06127593],
        [ 7.64836692],
        [11.67340482],
        [13.29500392],
        [12.38379

Magnitude: Tensor([[12.58320709],
        [13.3735577 ],
        [10.89456527],
        [12.03642077],
        [14.68681598],
        [14.83698444],
        [11.46279104],
        [10.58816272],
        [13.36851946],
        [12.896611  ],
        [12.26200497],
        [11.29676435],
        [13.86418821],
        [ 9.46399259],
        [10.9933223 ],
        [11.76627792],
        [12.7459709 ],
        [12.5787299 ],
        [11.69196977],
        [10.81440306],
        [13.57769462],
        [12.00767211],
        [11.30741497],
        [16.75064352],
        [14.38241942],
        [14.84074292],
        [10.81753875],
        [13.95566403],
        [11.67248134],
        [11.44117962],
        [11.36470909],
        [11.69059365]])
Tensor(nan)
Tensor(nan)
Magnitude: Tensor([[11.73500637],
        [14.27060039],
        [14.53800065],
        [10.007452  ],
        [12.02816352],
        [11.32868262],
        [11.34706558],
        [12.18576574],
        [ 9.84846859],
        [1

Tensor(-0.10025023)
Tensor(-0.09933715)
Magnitude: Tensor([[11.98214964],
        [12.76940841],
        [11.58715104],
        [10.18288041],
        [12.16394422],
        [14.32911055],
        [11.15540175],
        [13.8736082 ],
        [12.9404422 ],
        [10.17862595],
        [15.17490753],
        [10.61513133],
        [14.21398169],
        [13.02610405],
        [17.21241465],
        [10.03511394],
        [12.22899811],
        [14.07443523],
        [11.87212221],
        [12.98940678],
        [15.01235689],
        [11.05119448],
        [10.32836142],
        [13.94949131],
        [12.83283793],
        [14.7312389 ],
        [13.46407074],
        [15.19918542],
        [13.69670401],
        [12.3931762 ],
        [13.21720863],
        [10.08998593]])
Magnitude: Tensor([[11.04973503],
        [12.18605979],
        [12.94500636],
        [12.14360269],
        [12.01491796],
        [13.82630193],
        [11.70369906],
        [12.85733039],
        [15.74037

        [ 9.96989929]])
Tensor(-0.09468629)
Tensor(-0.0669706)
Magnitude: Tensor([[14.16826549],
        [11.99155345],
        [10.63766039],
        [16.20112948],
        [16.26360136],
        [12.24466843],
        [10.29005997],
        [13.02802915],
        [13.07775968],
        [14.42872522],
        [11.07538544],
        [11.80598241],
        [16.4760681 ],
        [ 8.96255468],
        [11.89668642],
        [13.81835693],
        [15.98316887],
        [11.84304357],
        [12.88152923],
        [11.69827782],
        [11.94104686],
        [11.51049088],
        [ 9.54463442],
        [11.3743744 ],
        [14.81243275],
        [11.09260782],
        [10.5567095 ],
        [12.15799365],
        [14.57622325],
        [12.58946964],
        [ 9.40030333],
        [10.85527716]])
Magnitude: Tensor([[10.2651634 ],
        [11.32549735],
        [13.71191669],
        [11.07941224],
        [13.18478874],
        [14.81968538],
        [13.33586822],
        [14.34039

        [12.2106166 ]])
Magnitude: Tensor([[12.01008862],
        [10.94226629],
        [15.52471054],
        [14.21644238],
        [16.75958825],
        [12.54636136],
        [13.12087508],
        [11.61518623],
        [12.64506616],
        [16.14671553],
        [11.93670866],
        [12.73141078],
        [12.18268239],
        [13.47207812],
        [13.43847269],
        [12.14405813],
        [14.40837789],
        [15.71034942],
        [12.02300447],
        [13.18177965],
        [11.96726846],
        [12.14592845],
        [12.79987983],
        [ 9.73619244],
        [13.38992541],
        [ 8.46727382],
        [12.82477748],
        [14.69544581],
        [ 9.66210755],
        [10.50628123],
        [13.12040436],
        [13.04279223]])
Tensor(nan)
Tensor(nan)
Magnitude: Tensor([[13.96564384],
        [13.82527668],
        [11.27608968],
        [12.94333559],
        [14.56279854],
        [10.96146738],
        [15.34186934],
        [14.01199043],
        [

        [10.97643251]])
Tensor(-0.10930357)
Tensor(-0.11279899)
Magnitude: Tensor([[14.31568777],
        [ 9.09566053],
        [10.53884005],
        [10.48573447],
        [12.31329602],
        [15.16774215],
        [13.05791044],
        [12.67997902],
        [13.2991446 ],
        [11.76733492],
        [13.61489822],
        [16.71048248],
        [13.1428857 ],
        [12.24080634],
        [ 9.96749604],
        [ 9.68119303],
        [10.02225999],
        [13.51621956],
        [10.13007077],
        [13.91049033],
        [16.00817485],
        [13.34726761],
        [16.28259483],
        [12.48310655],
        [13.74983099],
        [13.82357891],
        [14.52857747],
        [11.13839906],
        [14.28894004],
        [11.98785991],
        [11.11265034],
        [15.93107152]])
Magnitude: Tensor([[13.0463693 ],
        [12.24100272],
        [11.52973754],
        [10.36704777],
        [12.12443917],
        [14.27363617],
        [10.49564349],
        [15.3874

        [12.7634747 ]])
Magnitude: Tensor([[16.28344937],
        [11.81650337],
        [14.90866795],
        [11.32436238],
        [13.57088311],
        [10.71255821],
        [12.50471169],
        [ 9.91360218],
        [12.54004746],
        [14.89672615],
        [13.91013623],
        [12.65137626],
        [13.60861646],
        [11.75658808],
        [11.87308431],
        [11.42216434],
        [11.01527559],
        [11.00006309],
        [11.63953708],
        [11.07577292],
        [10.72175371],
        [11.34010218],
        [10.92640439],
        [12.74760759],
        [ 9.66644929],
        [15.09749651],
        [16.54813979],
        [10.7767428 ],
        [12.81179697],
        [11.9759405 ],
        [ 9.39426785],
        [12.07511702]])
Tensor(nan)
Tensor(nan)
Magnitude: Tensor([[10.09268035],
        [13.23907522],
        [12.44464505],
        [13.81036838],
        [ 9.90505522],
        [11.42590189],
        [13.58964179],
        [11.17877719],
        [

        [11.38704495]])
Magnitude: Tensor([[16.69036865],
        [11.93960151],
        [11.05172285],
        [12.92831875],
        [13.17104712],
        [12.90825598],
        [13.65102739],
        [11.54485072],
        [14.48050936],
        [10.65660951],
        [14.89517927],
        [ 9.41766835],
        [11.17622539],
        [10.67367986],
        [11.5400334 ],
        [14.91775786],
        [14.69116672],
        [10.358769  ],
        [14.08582075],
        [12.32530196],
        [12.41683074],
        [10.90506112],
        [15.24994993],
        [11.39051999],
        [10.22237376],
        [14.01425006],
        [13.09531545],
        [14.11029657],
        [14.68908034],
        [12.7399072 ],
        [14.64279373],
        [11.56364807]])
Tensor(-0.08103715)
Tensor(-0.09554613)
Magnitude: Tensor([[10.33768974],
        [11.90712074],
        [10.41828577],
        [12.25895548],
        [14.54871367],
        [11.12864836],
        [14.43631258],
        [10.4123

        [13.08280365]])
Tensor(nan)
Tensor(nan)
Magnitude: Tensor([[12.16649455],
        [11.92304317],
        [11.70134785],
        [11.99838031],
        [12.63203194],
        [14.92399399],
        [13.69624825],
        [10.8525723 ],
        [11.27258511],
        [12.52632765],
        [15.3235229 ],
        [11.99272459],
        [12.62431265],
        [ 9.68191089],
        [12.28096284],
        [11.33989407],
        [12.36092708],
        [11.68804361],
        [14.85296575],
        [10.71960506],
        [ 9.98263064],
        [11.58892543],
        [11.98752974],
        [12.47613184],
        [12.54171661],
        [14.7880487 ],
        [11.05478096],
        [12.89292279],
        [12.7439845 ],
        [11.66382743],
        [13.10318943],
        [ 9.30604728]])
Magnitude: Tensor([[10.03164629],
        [11.57005721],
        [11.08493788],
        [13.06074855],
        [ 9.1982436 ],
        [11.3797973 ],
        [12.21180577],
        [16.74304544],
        [

Tensor(-0.07607556)
Magnitude: Tensor([[14.74030315],
        [11.12396958],
        [10.61401761],
        [15.78881053],
        [12.26471672],
        [10.62428904],
        [13.06626149],
        [11.70937715],
        [12.10554864],
        [11.19248896],
        [11.17212663],
        [11.98306385],
        [11.74947355],
        [ 9.85816381],
        [13.42264634],
        [12.90625019],
        [12.26007884],
        [12.23402904],
        [12.53201755],
        [11.94102569],
        [15.9087021 ],
        [11.0771335 ],
        [11.21270348],
        [12.23984402],
        [13.37200655],
        [16.69235609],
        [10.94822503],
        [10.29784155],
        [11.20470171],
        [13.61493475],
        [14.26720217],
        [12.77223578]])
Magnitude: Tensor([[10.98364703],
        [11.77806847],
        [14.15977127],
        [11.03157142],
        [ 9.98111222],
        [12.31074041],
        [12.50036889],
        [ 8.30059178],
        [10.0954573 ],
        [11.86

Tensor(nan)
Magnitude: Tensor([[ 9.48947574],
        [13.95877308],
        [11.07475887],
        [13.64919763],
        [11.67392599],
        [12.3824831 ],
        [14.21077445],
        [14.96542576],
        [12.35883038],
        [ 9.79912609],
        [12.71524833],
        [13.98497144],
        [12.14566219],
        [16.90042653],
        [12.6727694 ],
        [11.23350279],
        [ 9.07938407],
        [10.05246633],
        [ 9.47574083],
        [14.53987608],
        [14.03271559],
        [13.10179682],
        [10.52438799],
        [13.63741332],
        [11.38128759],
        [13.91308314],
        [10.73169824],
        [12.15980447],
        [11.1130045 ],
        [12.77929365],
        [10.85954253],
        [13.98908744]])
Magnitude: Tensor([[11.51134016],
        [14.29787602],
        [14.67662252],
        [12.03134446],
        [11.00829664],
        [10.85036107],
        [12.65999821],
        [10.79878533],
        [12.19050866],
        [10.97037994],

Tensor(-0.08567917)
Tensor(-0.12290046)
Magnitude: Tensor([[11.16685147],
        [10.96024435],
        [12.63595396],
        [11.21034271],
        [14.48324349],
        [14.49047349],
        [12.30280111],
        [13.07709114],
        [12.74170263],
        [14.80862998],
        [12.81030341],
        [13.33264335],
        [12.46220216],
        [13.57550762],
        [12.81656716],
        [ 8.89719351],
        [12.84420954],
        [16.39066151],
        [11.64787922],
        [12.09975997],
        [ 9.83727322],
        [14.68578675],
        [13.1693493 ],
        [12.3591252 ],
        [11.54869666],
        [14.05139304],
        [11.50494667],
        [11.55217326],
        [10.90514748],
        [11.73694865],
        [15.0890762 ],
        [10.57027564]])
Magnitude: Tensor([[ 9.9442745 ],
        [13.78010595],
        [14.01773491],
        [11.5431578 ],
        [13.04134091],
        [11.12656029],
        [11.74179415],
        [14.96094146],
        [13.59773

Tensor(nan)
Magnitude: Tensor([[12.2727404 ],
        [12.91899628],
        [12.89564062],
        [10.27130839],
        [11.2634624 ],
        [10.90983264],
        [12.55354255],
        [12.4071697 ],
        [12.2614533 ],
        [12.69425751],
        [12.29882192],
        [11.5059033 ],
        [10.24452819],
        [12.44969294],
        [10.80240125],
        [12.36270638],
        [12.99963064],
        [12.69365814],
        [17.8843898 ],
        [11.78060455],
        [14.57455168],
        [11.22809913],
        [11.47719679],
        [14.02789523],
        [11.91291594],
        [16.27230908],
        [11.85256752],
        [13.13961603],
        [10.67185652],
        [11.40551491],
        [11.30159549],
        [13.10648608]])
Magnitude: Tensor([[11.57263165],
        [13.78016845],
        [10.90762801],
        [12.80660656],
        [11.53534156],
        [12.25817734],
        [11.49129522],
        [15.33957968],
        [13.68962638],
        [10.86306831],

Magnitude: Tensor([[13.52349009],
        [12.98958763],
        [12.5067102 ],
        [17.8074282 ],
        [13.956273  ],
        [ 9.42782754],
        [ 7.21802324],
        [12.07013063],
        [14.46668266],
        [14.30580627],
        [15.45513413],
        [11.49667057],
        [10.3534088 ],
        [11.27700972],
        [11.90115684],
        [11.62541918],
        [13.75762422],
        [10.62850981],
        [14.14958386],
        [14.05961261],
        [12.37289132],
        [12.61921083],
        [14.53308526],
        [14.44341768],
        [12.88667048],
        [11.19969229],
        [12.65487366],
        [12.18518151],
        [ 9.87562802],
        [14.00440207],
        [13.36705259],
        [11.8552719 ]])
Magnitude: Tensor([[12.8159132 ],
        [14.20078432],
        [11.44231173],
        [15.18758653],
        [14.69104167],
        [14.0060274 ],
        [10.77182262],
        [13.61631934],
        [11.55423038],
        [11.59152192],
        [16

        [ 9.94735761]])
Tensor(-0.05831201)
Tensor(-0.07765055)
Magnitude: Tensor([[12.05651451],
        [ 8.6078475 ],
        [ 9.85123821],
        [12.62268165],
        [11.35178877],
        [14.48913504],
        [14.4259479 ],
        [10.60378312],
        [10.46698669],
        [13.12286899],
        [12.1957278 ],
        [ 9.62563884],
        [11.85441488],
        [11.51247804],
        [11.8427656 ],
        [14.51520829],
        [13.62969876],
        [13.32693966],
        [15.26688313],
        [10.04426856],
        [11.76051666],
        [12.12230036],
        [15.97443738],
        [ 9.10583308],
        [12.21194041],
        [14.25581435],
        [13.70102556],
        [13.51514454],
        [11.73777484],
        [12.78358396],
        [11.49089775],
        [13.49500816]])
Magnitude: Tensor([[13.40730851],
        [11.86684596],
        [11.79055941],
        [10.77842072],
        [11.23906964],
        [12.48767103],
        [13.14788485],
        [15.2094

        [10.6082465 ]])
Magnitude: Tensor([[ 9.70443186],
        [10.21116531],
        [12.05192066],
        [17.6005634 ],
        [10.39621467],
        [ 8.36619298],
        [15.12622787],
        [13.44174476],
        [ 8.04134175],
        [ 9.70363641],
        [11.45090685],
        [ 9.66976245],
        [14.23320925],
        [13.56574358],
        [12.02829845],
        [15.1315466 ],
        [10.12762846],
        [13.80471614],
        [11.26372681],
        [13.18177965],
        [13.08867914],
        [12.15149161],
        [16.41557567],
        [10.77557358],
        [10.96629757],
        [12.4744411 ],
        [13.96737137],
        [12.56159481],
        [14.51386532],
        [10.67312814],
        [12.28072501],
        [12.60790678]])
Tensor(nan)
Tensor(nan)
Magnitude: Tensor([[14.74696794],
        [12.14915105],
        [14.15730491],
        [10.58366319],
        [12.8346966 ],
        [12.27587823],
        [10.78546577],
        [11.80500351],
        [

Magnitude: Tensor([[10.62192247],
        [14.41134186],
        [11.24799804],
        [14.54979418],
        [12.53750018],
        [12.19217045],
        [11.52893626],
        [12.1286169 ],
        [13.0092268 ],
        [12.68745578],
        [11.63318807],
        [14.63076837],
        [10.82225853],
        [12.53671731],
        [12.93639879],
        [10.44765098],
        [11.26972809],
        [11.04303803],
        [10.25131166],
        [12.56552363],
        [14.34164725],
        [16.66390748],
        [11.58261775],
        [12.17281289],
        [12.71398474],
        [11.95219471],
        [11.91512978],
        [10.14574726],
        [10.1658418 ],
        [12.98688606],
        [12.26981373],
        [11.54684487]])
Tensor(nan)
Tensor(nan)
Magnitude: Tensor([[10.80721465],
        [11.62554423],
        [12.62770341],
        [11.11846124],
        [12.63203194],
        [12.30672093],
        [ 9.97469295],
        [11.30974379],
        [12.94524535],
        [1

        [10.90899627]])
Magnitude: Tensor([[14.17752264],
        [11.21763742],
        [20.58108979],
        [15.51870441],
        [12.55539381],
        [10.13394439],
        [13.71667854],
        [13.3068207 ],
        [13.25607377],
        [14.06245306],
        [12.85381833],
        [16.67475112],
        [16.00476263],
        [13.67216465],
        [ 9.60888057],
        [ 9.41336651],
        [11.07941224],
        [14.70007041],
        [10.2653674 ],
        [12.24569805],
        [13.27800615],
        [13.06595531],
        [12.85344538],
        [ 8.29105744],
        [12.20952554],
        [15.18720396],
        [13.04199521],
        [12.5622774 ],
        [10.96802598],
        [14.23578652],
        [13.10696665],
        [12.15689115]])
Tensor(nan)
Tensor(nan)
Magnitude: Tensor([[13.62868787],
        [12.87743081],
        [13.66019758],
        [18.81215673],
        [12.74735792],
        [16.13029072],
        [11.13091066],
        [11.81212138],
        [

Tensor(-0.11698012)
Tensor(-0.09341443)
Magnitude: Tensor([[12.13916409],
        [11.5023182 ],
        [11.25200263],
        [10.63271113],
        [11.89759726],
        [11.06653282],
        [15.67349469],
        [ 9.72318463],
        [13.95690791],
        [14.16691876],
        [12.05794412],
        [11.53463943],
        [11.48398997],
        [10.97643251],
        [11.62078864],
        [13.75971377],
        [11.51899405],
        [14.826031  ],
        [13.15409202],
        [13.29667069],
        [11.23728227],
        [13.30828605],
        [11.29625851],
        [12.26577947],
        [12.31066383],
        [14.20370389],
        [10.08218263],
        [11.53516257],
        [12.4899927 ],
        [13.3874209 ],
        [16.61616017],
        [13.46305829]])
Magnitude: Tensor([[ 9.62524637],
        [10.77530671],
        [11.82340692],
        [13.20044195],
        [ 9.70038053],
        [13.51564351],
        [10.98315711],
        [12.3475146 ],
        [11.99089

Magnitude: Tensor([[13.18946487],
        [12.54181678],
        [11.39882788],
        [ 9.60795393],
        [14.67832477],
        [10.90352761],
        [13.3711116 ],
        [14.1676766 ],
        [13.01420544],
        [13.14936006],
        [11.02458955],
        [12.26625136],
        [12.43966865],
        [11.54962786],
        [10.88459106],
        [11.86484727],
        [11.84360664],
        [13.93373964],
        [13.83531472],
        [13.42264634],
        [15.3904627 ],
        [13.58477129],
        [14.1193625 ],
        [12.38436619],
        [10.52929894],
        [11.35573922],
        [11.32656158],
        [12.31754398],
        [12.19554042],
        [15.82087342],
        [ 9.99640479],
        [15.1245522 ]])
Magnitude: Tensor([[ 7.91378148],
        [10.84494007],
        [12.50393397],
        [14.05405378],
        [11.69046706],
        [10.16170263],
        [12.43244024],
        [11.74462295],
        [10.32028962],
        [11.85441488],
        [13

KeyboardInterrupt: 

In [61]:
# print(dot_good)
# print(dot_bad)
# print(w_bad)
# print(w_img)
print(bd_img)
print(np.linalg.norm(bw_good,axis=1))
print(bd_bad)

[[1.38372242 0.79107618 2.47902846 ... 1.77728534 1.84506273 1.9262557 ]
 [1.95013368 2.13824582 0.75338435 ... 0.06614064 1.81178069 0.76349992]
 [0.34629354 0.23912963 0.28421357 ... 0.67701119 0.35397545 2.34805465]
 ...
 [1.00953126 2.89725542 0.42719081 ... 0.57562923 0.09881391 0.05302662]
 [0.87503332 1.29086626 0.1983432  ... 0.42752948 0.60266405 0.44355509]
 [0.         1.32049751 0.02357272 ... 1.12617528 0.06949332 0.41221076]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1.]
[[0.28393805 0.62524104 0.14700276 ... 0.19647674 4.06395721 0.51066828]
 [0.45613325 1.80200303 0.6274848  ... 0.58377868 0.69437206 0.31062904]
 [1.30805516 0.74788821 1.31198823 ... 0.78026295 0.31707814 0.82756519]
 ...
 [0.29385543 0.01552426 0.2205736  ... 0.65662795 0.82849151 0.21491462]
 [1.55326176 0.61116642 3.88131714 ... 0.78870904 2.28962803 1.04799771]
 [0.74403208 1.24362862 0.10904855 ... 0.74419969 1.30684519 0.28500128]]
